---
- name: "Get Current Elastic version"
  uri:
    url: "http://{{es_host}}:{{es_http_port}}/"
    body_format: json
  changed_when: false
  register: nodeinfo
  ignore_errors: yes
  tags: always

- name: "Post migration tasks"
  include_tasks: post_steps.yml
  tags: post_steps
  when: upgrade_elastic

- name: "Pre migration tasks"
  include_tasks: pre_steps.yml
  tags: pre_steps
  when: (nodeinfo.failed != true) and (nodeinfo.json.version.number != es_version)