---
- name: "Exclude node from routing"
  uri:
    url: "http://{{es_host}}:{{es_http_port}}/_cluster/settings"
    method: "PUT"
    body: '{"transient" :{"cluster.routing.allocation.exclude._name": "{{nodeinfo.json.name}}"}}'
    body_format: json
  notify: reset transient

- name: unhold elastic package
  become: yes
  dpkg_selections:
    name: "elasticsearch"
    selection: "deinstall"

- name: "wait for end of Relocating"
  script: ../assets/check_relocating.py
  register: migrationstatus
  until: migrationstatus.stdout == "NOT RELOCATING"
  retries: 1200