---
- name: "Exclude node from routing"
  uri:
    url: "http://{{es_host}}:{{es_http_port}}/_cluster/settings"
    method: "PUT"
    body: "{\"transient\" :{\"cluster.routing.allocation.exclude._name\": \"{{nodeinfo.json.name}}\"}}"
  notify: reset transient

- name: "wait for end of Relocating"
  script: ../assets/check_relocating.py
  register: migrationstatus
  while: migrationstatus.stdout != "NOT RELOCATING"