---
- name: reset transient
  uri:
    url: "http://{{es_host}}:{{es_http_port}}/_cluster/settings"
    method: "PUT"
    body: '{"transient" :{"cluster.routing.allocation.exclude._name": null}}'
    body_format: json